import { Pipe, PipeTransform } from '@angular/core';
import { LanguageService } from '../services/language.service';

const DICT: Record<string, { ar: string; en: string }> = {
  // Navigation
  home: { ar: 'الرئيسية', en: 'Home' },
  projects_nav: { ar: 'المشاريع', en: 'Projects' },
  videos_nav: { ar: 'الفيديوهات', en: 'Videos' },
  account_nav: { ar: 'الحساب', en: 'Account' },
  programs_nav: { ar: 'البرامج', en: 'Programs' },
  courses_nav: { ar: 'الدورات', en: 'Courses' },
  branches_nav: { ar: 'الفروع', en: 'Branches' },
  complaints_nav: { ar: 'الشكاوى', en: 'Complaints' },
  login_nav: { ar: 'دخول', en: 'Login' },
  register_nav: { ar: 'سجل مجاناً', en: 'Register' },
  logout_btn: { ar: 'تسجيل خروج', en: 'Logout' },
  search_placeholder: { ar: 'ابحث عن الدورات والبرامج...', en: 'Search courses and programs...' },
  search_aria: { ar: 'ابحث', en: 'Search' },
  account_profile: { ar: 'الملف الشخصي', en: 'Profile' },
  social_accounts: { ar: 'حسابات التواصل', en: 'Social Accounts' },
  academy_branch: { ar: 'الأكاديمية والفرع', en: 'Academy & Branch' },
  contact_verify: { ar: 'التواصل والتحقق', en: 'Contact & Verification' },
  security_password: { ar: 'الأمان وكلمة المرور', en: 'Security & Password' },
  two_factor: { ar: 'المصادقة الثنائية', en: 'Two-Factor Authentication' },
  session: { ar: 'جلسة الدخول', en: 'Session' },
  upload_avatar: { ar: 'تغيير الصورة الشخصية', en: 'Change Profile Photo' },
  linkedin: { ar: 'LinkedIn', en: 'LinkedIn' },
  facebook: { ar: 'Facebook', en: 'Facebook' },
  choose_academy: { ar: 'اختر الأكاديمية', en: 'Choose Academy' },
  choose_branch: { ar: 'اختر الفرع', en: 'Choose Branch' },
  save: { ar: 'حفظ البيانات', en: 'Save' },
  email: { ar: 'البريد الإلكتروني', en: 'Email' },
  phone: { ar: 'رقم الهاتف', en: 'Phone' },
  send_code: { ar: 'إرسال رمز', en: 'Send Code' },
  confirm: { ar: 'تأكيد', en: 'Confirm' },
  current_password: { ar: 'كلمة المرور الحالية', en: 'Current Password' },
  new_password: { ar: 'كلمة المرور الجديدة', en: 'New Password' },
  change_password: { ar: 'تغيير كلمة المرور', en: 'Change Password' },
  enable_2fa: { ar: 'تفعيل المصادقة الثنائية', en: 'Enable 2FA' },
  disable_2fa: { ar: 'إلغاء المصادقة الثنائية', en: 'Disable 2FA' },
  logout: { ar: 'تسجيل الخروج', en: 'Logout' },
  last_login: { ar: 'آخر دخول:', en: 'Last login:' },
  upload_photo: { ar: 'رفع الصورة', en: 'Upload Photo' },
  courses: { ar: 'الدورات', en: 'Courses' },
  students: { ar: 'الطلاب', en: 'Students' },
  teachers: { ar: 'المدرسين', en: 'Teachers' },
  academies: { ar: 'الأكاديميات', en: 'Academies' },
  language: { ar: 'اللغة', en: 'Language' },
  arabic: { ar: 'العربية', en: 'Arabic' },
  english: { ar: 'الإنجليزية', en: 'English' },
  // Home hero
  hero_title_line1: { ar: 'تعلم بذكاء، وابدأ', en: 'Learn Smart, and Start' },
  hero_title_line2: { ar: 'مسيرتك المهنية الآن', en: 'Your Career Now' },
  hero_desc: { ar: 'دورات وبرامج مجانية عالية الجودة مع شهادات معتمدة ومحتوى عملي مركز.', en: 'Free, high-quality courses and programs with accredited certificates and focused practical content.' },
  hero_cta_start: { ar: 'ابدأ الآن مجاناً', en: 'Start Free Now' },
  hero_cta_browse: { ar: 'تصفح الدورات', en: 'Browse Courses' },
  hero_alt: { ar: 'التعلم', en: 'Students Learning' },
  // Features section
  features_title: { ar: 'لماذا أكاديمية الإبداع؟', en: 'Why Choose Our Academy?' },
  features_subtitle: { ar: 'منصة متكاملة لتطوير مهاراتك من الأساسيات إلى الإتقان، مع تجربة مستخدم حديثة ومحتوى عالي الجودة.', en: 'A comprehensive platform to develop your skills from basics to mastery, with a modern user experience and high-quality content.' },
  feature_1_title: { ar: 'تعلم سريع وحديث', en: 'Fast and Modern Learning' },
  feature_1_desc: { ar: 'مناهج عملية تركز على المهارات المطلوبة في سوق العمل.', en: 'Practical curricula focused on skills required in the job market.' },
  feature_2_title: { ar: 'شهادات معتمدة', en: 'Accredited Certificates' },
  feature_2_desc: { ar: 'احصل على شهادات موثوقة تعزز فرصك المهنية.', en: 'Get reliable certificates that enhance your career opportunities.' },
  feature_3_title: { ar: 'تجربة مستخدم متميزة', en: 'Outstanding User Experience' },
  feature_3_desc: { ar: 'واجهة أنيقة وسهلة الاستخدام مع دعم كامل للغة العربية.', en: 'Elegant and easy-to-use interface with full Arabic language support.' },
  feature_4_title: { ar: 'دعم فني مستمر', en: 'Continuous Technical Support' },
  feature_4_desc: { ar: 'فريق مخصص لمساعدتك طوال رحلة التعلم.', en: 'A dedicated team to help you throughout your learning journey.' },
  // About section
  about_us_title: { ar: 'من نحن', en: 'About Us' },
  about_us_desc: { ar: 'نلتزم بتقديم برامج تعليمية وتدريبية عالية الجودة تمكن الأفراد والمجتمعات من تحقيق أهدافهم.', en: 'We are committed to providing high-quality educational and training programs that enable individuals and communities to achieve their goals.' },
  about_initiative_title: { ar: 'عن المبادرة', en: 'About the Initiative' },
  about_initiative_desc: { ar: 'نلتزم بتقديم برامج تعليمية وتدريبية عالية الجودة تمكن الأفراد والمجتمعات من تحقيق أهدافهم.', en: 'We are committed to providing high-quality educational and training programs that enable individuals and communities to achieve their goals.' },
  about_academy_title: { ar: 'عن الأكاديمية', en: 'About the Academy' },
  about_academy_desc: { ar: 'تقدم أكاديميتنا برامج تدريبية شاملة مصممة لتلبية الاحتياجات المتطورة للقوى العاملة الحديثة.', en: 'Our academy offers comprehensive training programs designed to meet the evolving needs of the modern workforce.' },
  about_us_btn: { ar: 'من نحن', en: 'About Us' },
  trainers_btn: { ar: 'المدربين', en: 'Trainers' },
  // Courses section
  courses_section_title: { ar: 'الدورات الأكثر طلباً', en: 'Most in-demand courses' },
  courses_section_subtitle: { ar: 'اكتشف أفضل الدورات التي تعزز مهاراتك وتطور مسيرتك المهنية، مصممة بعناية لأقصى جودة وتأثير.', en: 'Discover top courses that enhance your skills and advance your career, carefully designed for maximum quality and impact.' },
  all_courses: { ar: 'جميع الدورات', en: 'All courses' },
  technology: { ar: 'التكنولوجيا', en: 'Technology' },
  business: { ar: 'الأعمال', en: 'Business' },
  design: { ar: 'التصميم', en: 'Design' },
  languages: { ar: 'اللغات', en: 'Languages' },
  self_development: { ar: 'التطوير الذاتي', en: 'Self development' },
  start_learning: { ar: 'ابدأ التعلم الآن', en: 'Start learning now' },
  view_all_courses: { ar: 'عرض جميع الدورات', en: 'View all courses' },
  // CTA section
  cta_title: { ar: 'ابدأ رحلة التعلم اليوم', en: 'Start Your Learning Journey Today' },
  cta_subtitle: { ar: 'انضم إلى آلاف المتعلمين وطور مهاراتك مع برامج تدريبية مجانية وشهادات معتمدة.', en: 'Join thousands of learners and develop your skills with free training programs and accredited certificates.' },
  my_account: { ar: 'حسابي', en: 'My Account' },
  register_now: { ar: 'سجل الآن', en: 'Register Now' },
  // Stats bar
  students_registered: { ar: 'طالب مسجل', en: 'Registered Students' },
  training_courses: { ar: 'دورة تدريبية', en: 'Training Courses' },
  certified_count: { ar: 'شهادة معتمدة', en: 'Certified Certificates' },
  countries: { ar: 'دولة', en: 'Countries' },
  // Videos page
  videos_hero_title: { ar: 'مكتبة الفيديوهات التعليمية', en: 'Educational Video Library' },
  videos_hero_subtitle: { ar: 'اكتشف مجموعة واسعة من الفيديوهات التعليمية المتخصصة', en: 'Discover a wide range of specialized educational videos' },
  search_video: { ar: 'ابحث عن فيديو...', en: 'Search for a video...' },
  upload_new_video: { ar: 'رفع فيديو جديد', en: 'Upload New Video' },
  no_videos_title: { ar: 'لا توجد فيديوهات متاحة حالياً', en: 'No videos available now' },
  no_videos_desc: { ar: 'نعمل على إضافة المزيد من الفيديوهات التعليمية. تحقق مرة أخرى قريباً!', en: 'We are adding more educational videos. Check back soon!' },
  educational: { ar: 'تعليمي', en: 'Educational' },
  available: { ar: 'متاح', en: 'Available' },
  video_id: { ar: 'معرف الفيديو:', en: 'Video ID:' },
  watch_video: { ar: 'مشاهدة الفيديو', en: 'Watch Video' },
  edit_video: { ar: 'تعديل الفيديو', en: 'Edit video' },
  delete_video: { ar: 'حذف الفيديو', en: 'Delete video' },
  edit_video_modal_title: { ar: 'تعديل محتوى الفيديو', en: 'Edit Video Content' },
  video_url_req: { ar: 'رابط الفيديو *', en: 'Video URL *' },
  enter_youtube_vimeo: { ar: 'https://www.youtube.com/watch?v=... أو https://vimeo.com/...', en: 'https://www.youtube.com/watch?v=... or https://vimeo.com/...' },
  video_url_hint: { ar: 'أدخل رابط YouTube أو Vimeo أو رابط فيديو مباشر', en: 'Enter a YouTube, Vimeo, or direct video URL' },
  video_desc: { ar: 'وصف الفيديو', en: 'Video Description' },
  // Branches page
  branches_title: { ar: 'فروعنا', en: 'Our Branches' },
  branches_desc: { ar: 'اكتشف فروعنا المنتشرة في مختلف المدن ومراكز التدريب المتخصصة', en: 'Discover our branches across cities and training centers' },
  add_branch: { ar: 'إضافة فرع جديد', en: 'Add New Branch' },
  no_branches_title: { ar: 'لا توجد فروع متاحة حالياً', en: 'No branches available now' },
  no_branches_desc: { ar: 'نعمل على إضافة المزيد من الفروع قريباً', en: 'We are adding more branches soon' },
  halls_title: { ar: 'قاعات / فصول الأكاديمية', en: 'Academy Halls / Classrooms' },
  edit: { ar: 'تعديل', en: 'Edit' },
  delete: { ar: 'حذف', en: 'Delete' },
  add_branch_modal_title: { ar: 'إضافة فرع جديد', en: 'Add New Branch' },
  add_branch_modal_desc: { ar: 'أدخل بيانات الفرع الجديد', en: 'Enter the new branch data' },
  select_academy_req: { ar: 'اختر الأكاديمية *', en: 'Select Academy *' },
  select_academy_opt: { ar: '-- اختر الأكاديمية --', en: '-- Select Academy --' },
  branch_name_req: { ar: 'اسم الفرع *', en: 'Branch Name *' },
  branch_name_2: { ar: 'اسم الفرع (2)', en: 'Branch Name (2)' },
  branch_address_req: { ar: 'عنوان الفرع *', en: 'Branch Address *' },
  mobile_req: { ar: 'الجوال *', en: 'Mobile *' },
  phone_opt: { ar: 'الهاتف', en: 'Phone' },
  whatsapp_opt: { ar: 'واتساب', en: 'Whatsapp' },
  email_opt: { ar: 'البريد الإلكتروني', en: 'Email' },
  cancel_btn: { ar: 'إلغاء', en: 'Cancel' },
  saving: { ar: 'جاري الحفظ...', en: 'Saving...' },
  save_changes_btn: { ar: 'حفظ التغييرات', en: 'Save Changes' },
  add_branch_submit: { ar: 'إضافة الفرع', en: 'Add Branch' },
  // Complaints page
  complaints_title: { ar: 'إدارة الشكاوى', en: 'Complaints Management' },
  complaints_desc: { ar: 'تتبّع وفلترة الشكاوى بسهولة مع عرض واضح وسريع.', en: 'Track and filter complaints easily with a clear, fast view.' },
  text_search: { ar: 'بحث نصي', en: 'Text Search' },
  search_in_title_desc: { ar: 'ابحث في العنوان أو الوصف', en: 'Search in title or description' },
  status_lbl: { ar: 'الحالة', en: 'Status' },
  all_statuses: { ar: 'كل الحالات', en: 'All statuses' },
  type_lbl: { ar: 'النوع', en: 'Type' },
  all_types: { ar: 'كل الأنواع', en: 'All types' },
  from_date: { ar: 'من تاريخ', en: 'From' },
  to_date: { ar: 'إلى تاريخ', en: 'To' },
  apply_filters: { ar: 'تطبيق', en: 'Apply' },
  reset_filters: { ar: 'إعادة ضبط', en: 'Reset' },
  error_prefix: { ar: 'حدث خطأ:', en: 'Error:' },
  student_lbl: { ar: 'الطالب:', en: 'Student:' },
  date_lbl: { ar: 'التاريخ:', en: 'Date:' },
  no_complaints_title: { ar: 'لا توجد شكاوى للعرض', en: 'No complaints to show' },
  no_complaints_sub: { ar: 'حاول تعديل فلاتر البحث أو أضف شكوى جديدة.', en: 'Try adjusting filters or add a new complaint.' },
  // Projects page
  featured_projects_title: { ar: 'مشاريع مميزة', en: 'Featured Projects' },
  featured_projects_subtitle: { ar: 'نماذج من المشاريع العملية التي ينجزها المتعلمون خلال البرامج والدورات', en: 'Practical projects completed by learners during programs and courses' },
  add_project: { ar: 'إضافة مشروع جديد', en: 'Add New Project' },
  loading: { ar: 'جاري التحميل…', en: 'Loading…' },
  fetch_projects_error: { ar: 'تعذّر جلب المشاريع، الرجاء المحاولة لاحقًا.', en: 'Failed to fetch projects, please try again later.' },
  edit_project: { ar: 'تعديل المشروع', en: 'Edit Project' },
  add_new_project: { ar: 'إضافة مشروع جديد', en: 'Add New Project' },
  project_name_ar: { ar: 'اسم المشروع بالعربية *', en: 'Project name in Arabic *' },
  project_name_ar_ph: { ar: 'أدخل اسم المشروع باللغة العربية', en: 'Enter project name in Arabic' },
  project_name_en_opt: { ar: 'اسم المشروع بالإنجليزية (اختياري)', en: 'Project name in English (optional)' },
  project_name_en_ph: { ar: 'Enter project name in English', en: 'Enter project name in English' },
  choose_branch_req: { ar: 'اختر الفرع *', en: 'Choose Branch *' },
  choose_branch_opt: { ar: 'اختر الفرع', en: 'Choose branch' },
  branches_loading: { ar: 'جاري تحميل الفروع...', en: 'Loading branches...' },
  project_start: { ar: 'تاريخ البداية *', en: 'Start Date *' },
  project_end: { ar: 'تاريخ النهاية *', en: 'End Date *' },
  resources_files_opt: { ar: 'ملفات الموارد (اختياري)', en: 'Resource Files (optional)' },
  allowed_files_hint: { ar: 'يمكن رفع ملفات PDF, Word, أو أرشيف مضغوط', en: 'You can upload PDF, Word, or compressed archive files' },
  project_file_opt: { ar: 'ملف المشروع (اختياري)', en: 'Project File (optional)' },
  project_desc_req: { ar: 'وصف المشروع *', en: 'Project Description *' },
  project_desc_ph: { ar: 'اكتب وصفاً مفصلاً للمشروع...', en: 'Write a detailed description of the project...' },
  cancel: { ar: 'إلغاء', en: 'Cancel' },
  /* saving defined once above; reuse */
  /* save_changes not needed globally; using save_changes_btn */
  add_project_submit: { ar: 'إضافة المشروع', en: 'Add Project' },
  preview_project: { ar: 'معاينة المشروع', en: 'Preview Project' },
  /* edit/delete defined once above; reuse */
  // Courses page
  search_courses: { ar: 'ابحث عن الدورات والبرامج...', en: 'Search courses and programs...' },
  search: { ar: 'بحث', en: 'Search' },
  add_new_program: { ar: 'إضافة برنامج جديد', en: 'Add New Program' },
  view_grid: { ar: 'شبكة', en: 'Grid' },
  view_list: { ar: 'قائمة', en: 'List' },
  loading_plain: { ar: 'جاري التحميل...', en: 'Loading...' },
  no_courses_title: { ar: 'لا توجد دورات متاحة حالياً', en: 'No courses available now' },
  no_courses_desc: { ar: 'نعمل على إضافة المزيد من الدورات والبرامج التعليمية. تحقق مرة أخرى قريباً!', en: 'We are adding more courses and programs. Check back soon!' },
  refresh_page: { ar: 'تحديث الصفحة', en: 'Refresh page' },
  weeks: { ar: 'أسابيع', en: 'weeks' },
  students_lbl: { ar: 'طالب', en: 'students' },
  main_program: { ar: 'البرنامج الرئيسي:', en: 'Main Program:' },
  course_type: { ar: 'نوع الدورة:', en: 'Course Type:' },
  course_number: { ar: 'رقم الدورة:', en: 'Course Number:' },
  edit_course: { ar: 'تعديل الدورة', en: 'Edit course' },
  delete_program: { ar: 'حذف البرنامج', en: 'Delete program' },
  prev: { ar: 'السابق', en: 'Previous' },
  next: { ar: 'التالي', en: 'Next' },
  page_of: { ar: 'صفحة {{page}} من {{total}}', en: 'Page {{page}} of {{total}}' },
  add_program_modal_title: { ar: 'إضافة برنامج جديد', en: 'Add New Program' },
  choose_main_program_req: { ar: 'اختر البرنامج الرئيسي *', en: 'Choose main program *' },
  choose_main_program_opt: { ar: 'اختر البرنامج الرئيسي', en: 'Choose main program' },
  no_main_programs: { ar: 'لا توجد برامج رئيسية متاحة', en: 'No main programs available' },
  name_ar_3_70: { ar: 'اسم البرنامج بالعربية (3-70 حرف) *', en: 'Program name in Arabic (3-70 chars) *' },
  must_be_3_70: { ar: 'يجب أن يكون بين 3 و 70 حرف', en: 'Must be between 3 and 70 chars' },
  name_en_optional: { ar: 'اسم البرنامج بالإنجليزية (اختياري)', en: 'Program name in English (optional)' },
  desc_optional: { ar: 'اكتب وصف البرنامج (اختياري)', en: 'Write program description (optional)' },
  /* cancel_btn defined once above; reuse */
  submit_add_program: { ar: 'إضافة البرنامج', en: 'Add Program' },
  edit_program_title: { ar: 'تعديل البرنامج', en: 'Edit Program' },
  /* save_changes_btn defined once above; reuse */
  // Programs page extras
  programs_desc: { ar: 'اكتشف برامجنا التدريبية المتخصصة والمصممة لتطوير مهاراتك المهنية', en: 'Discover our specialized training programs designed to develop your professional skills' },
  program_form_title: { ar: 'أدخل بيانات البرنامج الجديد', en: 'Enter the new program data' },
  program_desc_ph: { ar: 'أدخل وصف البرنامج', en: 'Enter program description' },
  program: { ar: 'برنامج', en: 'Program' },
  view_details: { ar: 'عرض التفاصيل', en: 'View Details' },
  no_description: { ar: 'بدون وصف', en: 'No description' },
  specialized_program: { ar: 'برنامج متخصص', en: 'Specialized Program' },
  certified: { ar: 'شهادة معتمدة', en: 'Certified' },
  // Login page
  login_title: { ar: 'تسجيل الدخول', en: 'Login' },
  login_intro: { ar: 'أدخل بريدك وكلمة المرور للحصول على صلاحية الدخول.', en: 'Enter your email and password to sign in.' },
  email_lbl: { ar: 'البريد الإلكتروني', en: 'Email' },
  password_lbl: { ar: 'كلمة المرور', en: 'Password' },
  logging_in: { ar: 'جارٍ الدخول...', en: 'Signing in...' },
  login_btn: { ar: 'دخول', en: 'Login' },
  // Register page
  register_title: { ar: 'إنشاء حساب جديد', en: 'Create a New Account' },
  register_subtitle: { ar: 'ابدأ رحلتك التعليمية اليوم مع نفس تجربة التصميم المتناسقة عبر المنصّة', en: 'Start your learning journey today with a consistent design experience across the platform' },
  first_name: { ar: 'الاسم الأول', en: 'First Name' },
  last_name: { ar: 'اسم العائلة', en: 'Last Name' },
  email_label: { ar: 'البريد الإلكتروني', en: 'Email' },
  mobile_number: { ar: 'رقم الجوال', en: 'Mobile Number' },
  academy_id_opt: { ar: 'معرّف الأكاديمية (academyDataId) - اختياري', en: 'Academy ID (academyDataId) - Optional' },
  branch_id_opt: { ar: 'معرّف الفرع (branchCodeId) - اختياري', en: 'Branch ID (branchCodeId) - Optional' },
  password_label: { ar: 'كلمة المرور', en: 'Password' },
  confirm_password: { ar: 'تأكيد كلمة المرور', en: 'Confirm Password' },
  registering: { ar: 'جارٍ التسجيل...', en: 'Registering...' },
  back_home: { ar: 'العودة للرئيسية', en: 'Back to Home' },
  // Upload page
  upload_title: { ar: 'رفع محتوى الجلسات', en: 'Upload Session Content' },
  upload_sub: { ar: 'رفع الفيديوهات والملفات التعليمية', en: 'Upload educational videos and files' },
  main_program_req: { ar: 'البرنامج الرئيسي *', en: 'Main Program *' },
  choose_program: { ar: 'اختر البرنامج', en: 'Choose program' },
  video_url_opt: { ar: 'رابط الفيديو (اختياري)', en: 'Video URL (optional)' },
  description_lbl: { ar: 'الوصف', en: 'Description' },
  add_short_desc: { ar: 'أضف وصفاً مختصراً...', en: 'Add a short description...' },
  session_tasks_pdf: { ar: 'مهام الجلسة (PDF)', en: 'Session Tasks (PDF)' },
  optional_lbl: { ar: '(اختياري)', en: '(Optional)' },
  click_choose_pdf: { ar: 'اضغط لاختيار ملف PDF', en: 'Click to choose a PDF file' },
  allowed_ext: { ar: 'الامتدادات المسموحة: PDF, DOC, DOCX', en: 'Allowed types: PDF, DOC, DOCX' },
  session_project_pdf: { ar: 'مشروع الجلسة (PDF)', en: 'Session Project (PDF)' },
  materials_pdf: { ar: 'المواد العلمية (PDF)', en: 'Materials (PDF)' },
  session_quiz_pdf: { ar: 'اختبار الجلسة (PDF)', en: 'Session Quiz (PDF)' },
  saving_dots: { ar: 'جارٍ الحفظ...', en: 'Saving...' },
  save_btn: { ar: 'حفظ', en: 'Save' },
  cancel_btn2: { ar: 'إلغاء', en: 'Cancel' },
  saved_success: { ar: 'تم الحفظ بنجاح!', en: 'Saved successfully!' },
  redirect_home_2s: { ar: 'سيتم توجيهك للصفحة الرئيسية خلال ثانيتين...', en: 'You will be redirected to the home page in 2 seconds...' },
  save_failed_prefix: { ar: 'فشل حفظ المحتوى:', en: 'Failed to save content:' },
  required_fields_error: { ar: 'يرجى ملء جميع الحقول المطلوبة.', en: 'Please fill in all required fields.' },
  passwords_mismatch: { ar: 'كلمتا المرور غير متطابقتين.', en: 'Passwords do not match.' },
  register_success: { ar: 'تم إنشاء الحساب بنجاح. سيتم تسجيل الدخول تلقائيًا...', en: 'Account created successfully. You will be signed in automatically...' },
  // Header translations
  'common.nav.home': { ar: 'الرئيسية', en: 'Home' },
  'common.nav.coursesPrograms': { ar: 'الدورات والبرامج', en: 'Courses & Programs' },
  'common.nav.services': { ar: 'الخدمات', en: 'Services' },
  'common.nav.trainers': { ar: 'المدربين', en: 'Trainers' },
  'common.nav.jobs': { ar: 'الوظائف', en: 'Jobs' },
  'common.search.placeholder': { ar: 'ابحث عن الدورات والبرامج...', en: 'Search courses and programs...' },
  'common.search.placeholderShort': { ar: 'بحث...', en: 'Search...' },
  'common.auth.login': { ar: 'دخول', en: 'Login' },
};

@Pipe({ name: 't', pure: false })
export class TranslatePipe implements PipeTransform {
  constructor(private lang: LanguageService) {}
  transform(key: string): string {
    const item = DICT[key];
    if (!item) return key;
    return this.lang.current === 'en' ? item.en : item.ar;
  }
}


